#!/usr/bin/env node

const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const readline = require("node:readline");
const { parseEnv } = require("./lib/env");

const ENV_PATH = path.join(__dirname, ".env");

function prompt(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function main() {
  console.log("\n======================================================");
  console.log("   Claude Code Stats - Machine Setup                  ");
  console.log("======================================================\n");

  // Check if .env already exists
  if (fs.existsSync(ENV_PATH)) {
    const env = parseEnv(ENV_PATH);
    if (env.MACHINE_ID) {
      console.log("This machine is already registered:\n");
      console.log(`   Machine ID:   ${env.MACHINE_ID}`);
      console.log(`   Machine Name: ${env.MACHINE_NAME || "(not set)"}\n`);
      console.log("To re-register, delete .env first and remove the old");
      console.log("machine file from data/machines/ to avoid double-counting.\n");
      process.exit(0);
    }
  }

  // Generate UUID
  const machineId = crypto.randomUUID();

  // Get machine name
  const hostname = os.hostname();
  let machineName = hostname;

  if (process.stdin.isTTY) {
    const answer = await prompt(`Machine name [${hostname}]: `);
    if (answer) machineName = answer;
  }

  // Write .env
  const envContent = [
    "# Generated by: npm run setup",
    "# Do not commit this file",
    `MACHINE_ID=${machineId}`,
    `MACHINE_NAME=${machineName}`,
    "",
  ].join("\n");

  fs.writeFileSync(ENV_PATH, envContent);

  console.log("\nMachine registered successfully!\n");
  console.log(`   Machine ID:   ${machineId}`);
  console.log(`   Machine Name: ${machineName}`);
  console.log(`   Saved to:     .env\n`);
  console.log("Next steps:");
  console.log("  1. Run: npm run stats");
  console.log("  2. Run: npm run push\n");
}

main().catch((err) => {
  console.error("\nError:", err.message);
  process.exit(1);
});
